# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ef4af301c8d5a8c4d4cbd8c9dd3dd7622fca433f3c67c99bc7072a66ca662d673fde44f1c592c77c8ea011d3f869d49f33ff5ebcc5eafe53a76bd5a6ec59d9f

test:
  secret_key_base: c6263501e55420bf019c135b2fbbd0610c9adad4b0f7cbe949c9fa3e4b42d0ac8d49c964640854d46e4b03b2eddf1e97646f5482b7c759785682f5ffb0e9ec24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
